# Generated by Django 3.0 on 2020-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='used',
        ),
    ]
