# Generated by Django 3.0 on 2020-10-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='dificulty',
            field=models.CharField(choices=[('D', 'Díficil'), ('M', 'Médio'), ('F', 'Fácil'), ('S', 'Super Fácil')], default='S', max_length=1),
        ),
    ]
