# Generated by Django 3.0 on 2020-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201026_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='conclusionDate',
            new_name='dateObjective',
        ),
    ]
