# Generated by Django 3.0 on 2020-10-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201027_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=240)),
                ('dateGoal', models.DateField()),
                ('description', models.CharField(max_length=2500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('dificulty', models.CharField(choices=[('D', 'Díficil'), ('M', 'Médio'), ('F', 'Fácil'), ('S', 'Super Fácil')], default='S', max_length=1)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Objective')),
            ],
        ),
    ]
