# Generated by Django 3.0 on 2020-10-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
