# Generated by Django 3.0 on 2020-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
